[project]

name = "jax-ifnt"
version = "0.1.9"
dependencies = [
    "jax",
    "jaxlib",
]
readme = "README.rst"
description = "Execute runtime assertions, indexing checks, and more if jax code is not traced."
